version: '3.8'

services:
  db:
    image: postgres:17
    container_name: ecoresiduos-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ecoresiduos
      POSTGRES_DB: ecoresiduos_db
    ports:
      - "5432:5432"
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
